//---------------------------------------------------------------------------
// Name    - APP.H
// Version - 1.4a
// Year    - 2000
// Author  - Rohin A Gosling
//
// Description
//
//   Main application loop declaration.
//
//---------------------------------------------------------------------------

#ifndef APP_H
#define APP_H

#include "BTYPES.H"

void MainLoop ( ProgramState *State, ModelData *Model, BridgeDataStruct *Bridge, WindowGeometry *Geo, LayoutConfig *Layout, ColorTheme *Colors, FileState *FileInfo );

#endif
